### ISSUE TITLE
Deprecated API for Gradle 5.0

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/nebula-grails-plugin#2]
Newer versions of gradle issue this warning when using this plugin:

> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

The relevant line from the stacktrace is [GrailsSourceSetConfigurator.groovy:65](https://github.com/nebula-plugins/nebula-grails-plugin/blob/master/src/main/groovy/com/netflix/nebula/grails/GrailsSourceSetConfigurator.groovy#L65)

**Comment by rpalcolea** [comment]
This is fixed now
